# Generated by Django 4.0.2 on 2022-02-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('phone_num', models.CharField(max_length=12)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.level')),
            ],
        ),
    ]
