# Generated by Django 4.0.2 on 2022-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0002_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='terms_agreed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
