# Generated by Django 4.0.2 on 2022-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0003_student_terms_agreed_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='terms_agreed',
            field=models.BooleanField(),
        ),
    ]
