# Generated by Django 4.0.2 on 2022-02-16 12:49

from django.db import migrations, models
import meta_app.forms


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0005_student_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[meta_app.forms.validate_phone])),
                ('message', models.CharField(blank=True, max_length=512, null=True)),
                ('spoken_with', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
