# Generated by Django 4.0.2 on 2022-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0009_alter_profile_linked_in_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='linked_in_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
