# Generated by Django 4.0.2 on 2022-02-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0011_alter_profile_linked_in_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='terms_agreed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=512)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
