# Generated by Django 4.0.2 on 2022-02-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0016_profile_city_profile_phone_numer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseByStudnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
