# Generated by Django 4.0.2 on 2022-02-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0018_profile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[(1, 'תלמיד'), (2, 'מורה')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
