# Generated by Django 4.0.2 on 2022-02-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0021_studentteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject', models.TextField(max_length=1028)),
                ('record_url', models.URLField(blank=True, null=True)),
                ('lesson_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='תלמיד', to='meta_app.profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='מורה', to='meta_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentTeacher',
        ),
    ]
