# Generated by Django 4.0.2 on 2022-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0022_studentteacherlesson_delete_studentteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://pngset.com/images/blue-person-icon-pictures-to-pin-pinsdaddy-blue-people-logo-symbol-hand-word-furniture-transparent-png-104501.png', max_length=1500, null=True, upload_to='meta_app/static/images'),
        ),
    ]
