# Generated by Django 4.0.2 on 2022-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0025_studentteacherlesson_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacherlesson',
            name='lesson_material',
            field=models.URLField(blank=True, null=True),
        ),
    ]
