# Generated by Django 4.0.2 on 2022-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0026_alter_studentteacherlesson_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', max_length=1500, null=True, upload_to='meta_app/static/images'),
        ),
    ]
